language: node_js
node_js:
  - 14

env:
- BUILD_NAME=bd

install:
- npm install

branches:
  only:
  - main
  - "/^ci-.*$/"

notifications:
  email:
    recipients:
      - $EMAIL_SELF
    on_success: change # default: change
    on_failure: always # default: always

stages:
  - test
  - name: page
    if: commit_message =~ /pub\s+page/
  - name: deploy
    if: commit_message =~ /deploy/

_share: &share
  before_install:
    - openssl aes-256-cbc -K $encrypted_db599200e721_key -iv $encrypted_db599200e721_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
    - chmod 600 ~/.ssh/id_rsa
    - echo -e "Host $HOST_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  script:
    - npm run $BUILD_NAME
    - ls
    - ssh travis@$HOST_IP -p $HOST_PORT "rm -rf ~/$TRAVIS_BRANCH && mkdir $TRAVIS_BRANCH"
    - scp  -P $HOST_PORT -r dist/ travis@$HOST_IP:~/$TRAVIS_BRANCH/
    - ssh travis@$HOST_IP -p $HOST_PORT "echo 'replace your exec';"

jobs:
  exclude:
    - if: branch = dev OR commit_message =~ /(no-ci)/
  include:
    - stage: test
      script: npm run test
    - stage: page
      script: npm run $BUILD_NAME && mv dist/ /tmp/demo
      deploy:
        provider: pages
        cleanup: true
        local_dir: /tmp/demo
        token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
        on:
          branch: main

    - stage: deploy
      <<: *share
      if: branch IN (main, qa, pl)




