language: node_js
node_js:
  - 14

env:
- BUILD_NAME=build

install:
- npm install

branches:
  only:
  - main
  - "/^ci-.*$/"

stages:
  - test
  - name: publish
    if: commit_message =~ /release/

jobs:
  exclude:
    - if: branch = dev OR commit_message =~ /(no-ci)/
  include:
    - stage: test
      script: npm run test

    - stage: publish
      script:
      - npm run $BUILD_NAME
      - ls
      - ssh travis@$HOST_IP -p $HOST_PORT "rm -rf ~/demo && mkdir demo"
      - scp  -P $HOST_PORT -r dist/ travis@$HOST_IP:~/demo/
      - ssh travis@$HOST_IP -p $HOST_PORT "echo 'replace your exec';"

before_install:
- openssl aes-256-cbc -K $encrypted_db599200e721_key -iv $encrypted_db599200e721_iv -in id_rsa.enc -out ~/.ssh/id_rsa -d
- chmod 600 ~/.ssh/id_rsa
- ls -al ~/.ssh
- echo -e "Host $HOST_IP\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config

